# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polygon_generator_gui_folder/designer_polygon_generator_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_left = QtWidgets.QWidget(self.centralwidget)
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_background_colour = QtWidgets.QWidget(self.widget_left)
        self.widget_background_colour.setObjectName("widget_background_colour")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_background_colour)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_select_background_colour = QtWidgets.QPushButton(self.widget_background_colour)
        self.button_select_background_colour.setObjectName("button_select_background_colour")
        self.horizontalLayout_2.addWidget(self.button_select_background_colour)
        self.label_background_colour = QtWidgets.QLabel(self.widget_background_colour)
        self.label_background_colour.setAutoFillBackground(True)
        self.label_background_colour.setText("")
        self.label_background_colour.setObjectName("label_background_colour")
        self.horizontalLayout_2.addWidget(self.label_background_colour)
        self.verticalLayout_2.addWidget(self.widget_background_colour)
        self.widget_shape_colour = QtWidgets.QWidget(self.widget_left)
        self.widget_shape_colour.setObjectName("widget_shape_colour")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_shape_colour)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button_select_shape_colour = QtWidgets.QPushButton(self.widget_shape_colour)
        self.button_select_shape_colour.setObjectName("button_select_shape_colour")
        self.horizontalLayout_12.addWidget(self.button_select_shape_colour)
        self.label_shape_colour = QtWidgets.QLabel(self.widget_shape_colour)
        self.label_shape_colour.setAutoFillBackground(True)
        self.label_shape_colour.setText("")
        self.label_shape_colour.setObjectName("label_shape_colour")
        self.horizontalLayout_12.addWidget(self.label_shape_colour)
        self.verticalLayout_2.addWidget(self.widget_shape_colour)
        self.widget_polygon_type = QtWidgets.QWidget(self.widget_left)
        self.widget_polygon_type.setObjectName("widget_polygon_type")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_polygon_type)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_polygon_type = QtWidgets.QLabel(self.widget_polygon_type)
        self.label_polygon_type.setObjectName("label_polygon_type")
        self.horizontalLayout_3.addWidget(self.label_polygon_type)
        self.radioButton_convex = QtWidgets.QRadioButton(self.widget_polygon_type)
        self.radioButton_convex.setChecked(True)
        self.radioButton_convex.setObjectName("radioButton_convex")
        self.horizontalLayout_3.addWidget(self.radioButton_convex)
        self.radioButton_concave = QtWidgets.QRadioButton(self.widget_polygon_type)
        self.radioButton_concave.setObjectName("radioButton_concave")
        self.horizontalLayout_3.addWidget(self.radioButton_concave)
        self.verticalLayout_2.addWidget(self.widget_polygon_type)
        self.widget_number_of_vertices = QtWidgets.QWidget(self.widget_left)
        self.widget_number_of_vertices.setObjectName("widget_number_of_vertices")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_number_of_vertices)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_number_of_vertices = QtWidgets.QLabel(self.widget_number_of_vertices)
        self.label_number_of_vertices.setObjectName("label_number_of_vertices")
        self.horizontalLayout_5.addWidget(self.label_number_of_vertices)
        self.spinBox_number_of_vertices = QtWidgets.QSpinBox(self.widget_number_of_vertices)
        self.spinBox_number_of_vertices.setMinimum(1)
        self.spinBox_number_of_vertices.setMaximum(99)
        self.spinBox_number_of_vertices.setProperty("value", 5)
        self.spinBox_number_of_vertices.setObjectName("spinBox_number_of_vertices")
        self.horizontalLayout_5.addWidget(self.spinBox_number_of_vertices)
        self.verticalLayout_2.addWidget(self.widget_number_of_vertices)
        self.widget_sample_polugon_refresh = QtWidgets.QWidget(self.widget_left)
        self.widget_sample_polugon_refresh.setObjectName("widget_sample_polugon_refresh")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_sample_polugon_refresh)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_draw_sample_polygon = QtWidgets.QPushButton(self.widget_sample_polugon_refresh)
        self.button_draw_sample_polygon.setObjectName("button_draw_sample_polygon")
        self.gridLayout_3.addWidget(self.button_draw_sample_polygon, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_sample_polugon_refresh)
        self.widget_image_size = QtWidgets.QWidget(self.widget_left)
        self.widget_image_size.setObjectName("widget_image_size")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_image_size)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_image_width = QtWidgets.QLabel(self.widget_image_size)
        self.label_image_width.setObjectName("label_image_width")
        self.horizontalLayout_8.addWidget(self.label_image_width)
        self.spinBox_image_width = QtWidgets.QSpinBox(self.widget_image_size)
        self.spinBox_image_width.setMaximum(1000)
        self.spinBox_image_width.setProperty("value", 480)
        self.spinBox_image_width.setObjectName("spinBox_image_width")
        self.horizontalLayout_8.addWidget(self.spinBox_image_width)
        self.verticalLayout_2.addWidget(self.widget_image_size)
        self.widget_image_height = QtWidgets.QWidget(self.widget_left)
        self.widget_image_height.setObjectName("widget_image_height")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_image_height)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_image_height = QtWidgets.QLabel(self.widget_image_height)
        self.label_image_height.setObjectName("label_image_height")
        self.horizontalLayout_9.addWidget(self.label_image_height)
        self.spinBox_image_height = QtWidgets.QSpinBox(self.widget_image_height)
        self.spinBox_image_height.setMaximum(1000)
        self.spinBox_image_height.setProperty("value", 480)
        self.spinBox_image_height.setObjectName("spinBox_image_height")
        self.horizontalLayout_9.addWidget(self.spinBox_image_height)
        self.verticalLayout_2.addWidget(self.widget_image_height)
        self.widget_number_of_images_to_generate = QtWidgets.QWidget(self.widget_left)
        self.widget_number_of_images_to_generate.setObjectName("widget_number_of_images_to_generate")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_number_of_images_to_generate)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_number_of_images_to_generate = QtWidgets.QLabel(self.widget_number_of_images_to_generate)
        self.label_number_of_images_to_generate.setObjectName("label_number_of_images_to_generate")
        self.horizontalLayout_11.addWidget(self.label_number_of_images_to_generate)
        self.spinBox_number_of_images_to_generate = QtWidgets.QSpinBox(self.widget_number_of_images_to_generate)
        self.spinBox_number_of_images_to_generate.setMaximum(1000)
        self.spinBox_number_of_images_to_generate.setProperty("value", 10)
        self.spinBox_number_of_images_to_generate.setObjectName("spinBox_number_of_images_to_generate")
        self.horizontalLayout_11.addWidget(self.spinBox_number_of_images_to_generate)
        self.verticalLayout_2.addWidget(self.widget_number_of_images_to_generate)
        self.widget_file_save_format = QtWidgets.QWidget(self.widget_left)
        self.widget_file_save_format.setObjectName("widget_file_save_format")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_file_save_format)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_file_save_format = QtWidgets.QLabel(self.widget_file_save_format)
        self.label_file_save_format.setObjectName("label_file_save_format")
        self.horizontalLayout_6.addWidget(self.label_file_save_format)
        self.comboBox_files_save_format = QtWidgets.QComboBox(self.widget_file_save_format)
        self.comboBox_files_save_format.setObjectName("comboBox_files_save_format")
        self.comboBox_files_save_format.addItem("")
        self.comboBox_files_save_format.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_files_save_format)
        self.verticalLayout_2.addWidget(self.widget_file_save_format)
        self.widget_folder_to_save_to = QtWidgets.QWidget(self.widget_left)
        self.widget_folder_to_save_to.setObjectName("widget_folder_to_save_to")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_folder_to_save_to)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_select_folder_to_save_images_to = QtWidgets.QPushButton(self.widget_folder_to_save_to)
        self.button_select_folder_to_save_images_to.setObjectName("button_select_folder_to_save_images_to")
        self.verticalLayout_3.addWidget(self.button_select_folder_to_save_images_to)
        self.label_selected_folder_to_save_to = QtWidgets.QLabel(self.widget_folder_to_save_to)
        self.label_selected_folder_to_save_to.setText("")
        self.label_selected_folder_to_save_to.setObjectName("label_selected_folder_to_save_to")
        self.verticalLayout_3.addWidget(self.label_selected_folder_to_save_to)
        self.verticalLayout_2.addWidget(self.widget_folder_to_save_to)
        self.widget_generate_images = QtWidgets.QWidget(self.widget_left)
        self.widget_generate_images.setObjectName("widget_generate_images")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_generate_images)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_generate_images = QtWidgets.QPushButton(self.widget_generate_images)
        self.pushButton_generate_images.setObjectName("pushButton_generate_images")
        self.horizontalLayout_10.addWidget(self.pushButton_generate_images)
        self.verticalLayout_2.addWidget(self.widget_generate_images)
        self.horizontalLayout.addWidget(self.widget_left)
        self.widget_right = QtWidgets.QWidget(self.centralwidget)
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_sample_polygon_image = QtWidgets.QWidget(self.widget_right)
        self.widget_sample_polygon_image.setObjectName("widget_sample_polygon_image")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_sample_polygon_image)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_sample_polygon_image = QtWidgets.QLabel(self.widget_sample_polygon_image)
        self.label_sample_polygon_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sample_polygon_image.setObjectName("label_sample_polygon_image")
        self.gridLayout.addWidget(self.label_sample_polygon_image, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_sample_polygon_image)
        self.horizontalLayout.addWidget(self.widget_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.menuHelp.addAction(self.actionInstructions)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)

        """
        tool tips
        """
        self.label_image_width.setToolTip("Set the width (0-1000) of the images that will be generated")
        self.label_image_height.setToolTip("Set the height (0-1000) of the images that will be generated")
        self.label_number_of_images_to_generate.setToolTip("Set the number of images (up to 1000) to be generated")
        self.label_file_save_format.setToolTip("Select the file format for the generated images to be saved as")
        self.button_select_folder_to_save_images_to.setToolTip("Select a folder for the generated images to be saved")
        self.pushButton_generate_images.setToolTip("Generate and save images of polygons to the selected folder in")
        self.button_draw_sample_polygon.setToolTip("Draw a sample polygon with the current settings")
        self.label_number_of_vertices.setToolTip("Select the number (1-99) of vertices for the polygon to have")
        self.label_polygon_type.setToolTip("Select the type of polygon to generate")
        self.button_select_shape_colour.setToolTip('Select polygon colour')
        self.button_select_background_colour.setToolTip('Select image background colour')

        """
        Do connections here
        So for this, need to link what happens when there is some change in the gui to a method that is in the
        MainWindow class, and in the MainWindow class, the methods are able to reference the values from the gui that
        come from buttons and the like
        """

        self.actionInstructions.triggered.connect(MainWindow.instructions_window)
        self.actionAbout.triggered.connect(MainWindow.about_window)

        self.button_select_background_colour.clicked.connect(MainWindow.set_background_colour)
        self.button_select_shape_colour.clicked.connect(MainWindow.set_shape_colour)

        self.radioButton_concave.toggled.connect(MainWindow.set_generator_to_concave)
        self.radioButton_convex.toggled.connect(MainWindow.set_generator_to_convex)

        self.spinBox_number_of_vertices.valueChanged.connect(MainWindow.set_number_of_vertices)
        self.spinBox_image_width.valueChanged.connect(MainWindow.set_image_width)
        self.spinBox_image_height.valueChanged.connect(MainWindow.set_image_height)
        self.spinBox_number_of_images_to_generate.valueChanged.connect(MainWindow.set_number_of_images_to_generate)
        self.comboBox_files_save_format.activated[str].connect(MainWindow.select_file_save_format)

        self.button_draw_sample_polygon.clicked.connect(MainWindow.draw_sample_polygon)

        self.button_select_folder_to_save_images_to.clicked.connect(MainWindow.set_folder_to_save_to)

        self.pushButton_generate_images.clicked.connect(MainWindow.generate_images)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Polygon Generator"))
        self.button_select_background_colour.setText(_translate("MainWindow", "Select background colour"))
        self.button_select_shape_colour.setText(_translate("MainWindow", "Select shape colour"))
        self.label_polygon_type.setText(_translate("MainWindow", "Polygon type"))
        self.radioButton_convex.setText(_translate("MainWindow", "Convex"))
        self.radioButton_concave.setText(_translate("MainWindow", "Concave"))
        self.label_number_of_vertices.setText(_translate("MainWindow", "Number of vertices"))
        self.button_draw_sample_polygon.setText(_translate("MainWindow", "Draw sample polygon"))
        self.label_image_width.setText(_translate("MainWindow", "Image width"))
        self.label_image_height.setText(_translate("MainWindow", "Image height"))
        self.label_number_of_images_to_generate.setText(_translate("MainWindow", "Number of images to generate"))
        self.label_file_save_format.setText(_translate("MainWindow", "File save format"))
        self.comboBox_files_save_format.setItemText(0, _translate("MainWindow", "jpg"))
        self.comboBox_files_save_format.setItemText(1, _translate("MainWindow", "png"))
        self.button_select_folder_to_save_images_to.setText(_translate("MainWindow", "Select folder to save images to"))
        self.pushButton_generate_images.setText(_translate("MainWindow", "Generate images"))
        self.label_sample_polygon_image.setText(_translate("MainWindow", "Sample polygon image"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))

